const fs = require('fs');
const read = name => fs.readFileSync(name, 'utf8');
const write = (name, value) => fs.writeFileSync(name, value, 'utf8');
const base = read('about.html');
const nav = page => `<header class="site-header"><div class="container nav">
<a class="brand" href="index.html" aria-label="Mays Suhail, home"><span class="brand-mark">m.</span><span>Mays Suhail<span class="brand-dot">.</span></span></a>
<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="primary-nav" hidden>Menu <span aria-hidden="true">☰</span></button>
<nav id="primary-nav" aria-label="Main navigation">${[['index','Home'],['services','Services'],['projects','Projects'],['about','About'],['journey','Journey'],['contact','Contact']].map(([key,label])=>`<a href="${key}.html"${key===page?' aria-current="page"':''}>${label}</a>`).join('')}</nav>
<div class="nav-actions"><button class="theme-toggle" type="button" data-theme-toggle aria-label="Switch color theme"><span aria-hidden="true">☾</span></button><a class="nav-cta" href="contact.html">Let’s talk <span aria-hidden="true">↗</span></a></div>
</div></header>`;
const footer = base.match(/<footer[\s\S]*?<\/footer>/)[0];
const cta = `<section class="contact-banner" data-reveal><div><p class="eyebrow">Your next project starts here</p><h2>Let’s build something together.</h2><p>Share your idea, timeline, and what success looks like for you.</p></div><a class="button button-light" href="contact.html">Discuss your project ↗</a></section>`;
const page = (key, title, description, content) => {
 const head = base.slice(0,base.indexOf('<body>')).replace(/<title>.*?<\/title>/,`<title>${title} | Mays Suhail</title>`).replace(/<meta name="description"[^>]*>/,`<meta name="description" content="${description}">`).replace(/<meta property="og:title"[^>]*>/,`<meta property="og:title" content="${title} | Mays Suhail">`).replace(/<meta property="og:description"[^>]*>/,`<meta property="og:description" content="${description}">`);
 write(key+'.html',head+`<body><div class="ambient" aria-hidden="true"></div><a class="skip-link" href="#main">Skip to content</a>${nav(key)}<main id="main" class="container">${content}</main>${footer}</body></html>`);
};
page('about','About Mays','Mays Suhail: Software Engineering graduate from Middle East University, freelance developer and creative based in Amman, Jordan.',`
<section class="page-intro" data-reveal><p class="eyebrow">The person behind the pixels</p><h1>Engineering meets<br><em>a creative eye.</em></h1><p class="lead">I’m Mays Suhail, a software engineer and freelance creative based in Amman, Jordan.</p></section>
<section class="about-layout"><div class="monogram-card" aria-hidden="true"><span class="monogram">ms.</span><span class="monogram-label">MAYS SUHAIL<br>CODE + CREATIVITY</span><span class="monogram-star">✦</span></div><div class="about-story" data-reveal><p class="eyebrow">A little about me</p><h2>Technical thinking.<br>Creative expression.</h2><p>I graduated in Software Engineering from Middle East University with a “Very Good” GPA rating. My interests connect web and mobile development with visual design.</p><p>My projects range from interactive websites to a Disaster Management graduation project with Flutter, React, and a Spring Boot API. I enjoy connecting the interface people see with the logic that makes it work.</p><p>I also joined the media section at JUST Programming Chapter as a freelance graphic designer and video editor. That creative perspective shapes the way I approach digital experiences.</p><div class="actions"><a class="button button-light" href="contact.html">Let’s work together ↗</a><a class="text-link" href="journey.html">My learning journey ↗</a></div></div></section>
<section class="services-section"><div class="section-heading" data-reveal><div><p class="eyebrow">What I bring</p><h2>More than a single skill.</h2></div></div><div class="principle-grid"><article data-reveal><span class="service-icon" aria-hidden="true">&lt;/&gt;</span><h3>Web &amp; application development</h3><p>Hands-on project experience with React, JavaScript, Flutter, Java, and Spring Boot.</p><a class="text-link" href="projects.html">Explore the work ↗</a></article><article data-reveal><span class="service-icon" aria-hidden="true">✧</span><h3>Design &amp; visual storytelling</h3><p>Graphic design, video editing, and motion graphics alongside interface design.</p><a class="text-link" href="services.html">Explore creative services ↗</a></article><article data-reveal><span class="service-icon" aria-hidden="true">↔</span><h3>Arabic &amp; English interfaces</h3><p>Projects that explore both reading directions, multilingual content, and thoughtful layout.</p><a class="text-link" href="project-dms.html">See the graduation project ↗</a></article></div></section>
<section class="profile-details" data-reveal><div><p class="eyebrow">A few personal details</p><h2>Based in Amman.<br>Open to your next idea.</h2></div><dl class="facts"><div><dt>Location</dt><dd>Amman, Jordan</dd></div><div><dt>Languages</dt><dd>Arabic · Native<br>English · Professional proficiency<br>French · Limited proficiency</dd></div><div><dt>Community</dt><dd>Volunteering with The Children’s Museum Jordan.</dd></div><div><dt>Working together</dt><dd>Available for freelance inquiries.</dd></div></dl></section>
${cta}`);

const credentials = [
 ['2025','Ethical Hacking Bootcamp','GDG on Campus – HTU'],
 ['2025','QA Software Testing','The Hope International Edu'],
 ['2024','UI/UX Design','The Hope International Edu'],
 ['2024','Piscine','42 Amman'],
 ['2023','Motion Graphic','SAE Institute Amman'],
 ['2023','Graphic Design','SAE Institute Amman'],
 ['2022','Frontend Development','The Hope International Edu'],
 ['2022','Python AI / Machine Learning','The Hope International Edu']
];
page('journey','Education & creative journey','Explore Mays Suhail’s education, design experience, and training in development, UI/UX, quality assurance, and security.',`
<section class="page-intro" data-reveal><p class="eyebrow">Learning is part of the work</p><h1>A foundation in code.<br><em>A curiosity for more.</em></h1><p class="lead">The education, creative work, and training that inform what I make.</p></section>
<section class="timeline-section"><div class="section-heading"><div><p class="eyebrow">Education &amp; experience</p><h2>Milestones along the way.</h2></div></div><div class="timeline"><article data-reveal><span class="timeline-date">Education</span><div><h3>BSc in Software Engineering</h3><p>Middle East University, Jordan · Very Good GPA</p><p>Graduation project: Disaster Management System.</p><a class="text-link" href="project-dms.html">Explore the project ↗</a></div></article><article data-reveal><span class="timeline-date">Creative work</span><div><h3>Freelance graphic designer &amp; video editor</h3><p>Media Section · JUST Programming Chapter</p><a class="text-link" href="https://www.linkedin.com/posts/mayssuhail_justprogramming-graphicdesign-videoediting-activity-7254399627616047104-swae" target="_blank" rel="noopener noreferrer">My announcement on LinkedIn ↗</a></div></article></div></section>
<section class="services-section"><div class="section-heading"><div><p class="eyebrow">Selected training</p><h2>Keeping the toolkit growing.</h2></div><a class="text-link" href="https://www.linkedin.com/in/mayssuhail/" target="_blank" rel="noopener noreferrer">Details on LinkedIn ↗</a></div><div class="credentials-grid">${credentials.map(([year,title,issuer])=>`<article class="credential" data-reveal><span class="credential-year">${year}</span><h3>${title}</h3><p>${issuer}</p></article>`).join('')}</div></section>${cta}`);

const projects = [
 {name:'Disaster Management System',repo:'DMS',cat:'web mobile backend',type:'Graduation project',symbol:'◎',text:'Flutter and React experiences connected to a Spring Boot API, with incident reporting, maps, SOS, and resource management.',tags:['Flutter','React','Spring Boot'],details:true},
 {name:'MediConnect AI',repo:'MediConnect-AI',cat:'web backend',type:'Portfolio demo · In development',symbol:'✳',text:'An Arabic/English clinic-management demonstration with appointments, access controls, and an informational AI assistant. Uses fictional data; some modules remain in progress.',tags:['Java','React / TypeScript','PostgreSQL']},
 {name:'Dynamic Car Management',repo:'Dynamic-Car-Management-App',cat:'web',type:'Interactive web app',symbol:'↔',text:'Add and remove car records, retain them in local storage, and switch between Arabic and English layouts.',tags:['JavaScript','HTML / CSS','Local storage']},
 {name:'Library Management System',repo:'Library_Management_System',cat:'backend',type:'Java application',symbol:'▤',text:'A Java and JDBC project covering book catalogs, borrowing, returns, user roles, and overdue fine calculations.',tags:['Java','JDBC','SQL']},
 {name:'Food Recipes',repo:'Food_RecipesReactAPP',cat:'web',type:'React project',symbol:'◉',text:'A recipe-themed application exploring React components and JavaScript interfaces.',tags:['React','JavaScript','CSS']},
 {name:'Travel Website',repo:'Travel-website',cat:'web',type:'Multi-page website',symbol:'△',text:'Destinations, travel tips, and a gallery organized with semantic HTML and accessible content structure.',tags:['HTML5','CSS','Accessibility']},
 {name:'Simple Ecommerce App',repo:'simple_ecommerce_app',cat:'mobile',type:'Flutter project',symbol:'▱',text:'A Flutter and Dart project exploring a mobile ecommerce application.',tags:['Flutter','Dart']}
];
page('projects','Projects','Explore Mays Suhail’s web, mobile, and backend projects, including her Disaster Management graduation project.',`
<section class="page-intro" data-reveal><p class="eyebrow">A collection of things I build</p><h1>Curiosity, turned<br><em>into working ideas.</em></h1><p class="lead">Explore my academic and personal projects. Each one is a different opportunity to learn, solve, and create.</p></section>
<div class="project-toolbar"><div class="project-filters" role="group" aria-label="Filter projects" hidden>${[['all','All projects'],['web','Web'],['mobile','Mobile'],['backend','Backend']].map(([key,label])=>`<button type="button" data-filter="${key}" aria-pressed="${key==='all'}">${label}</button>`).join('')}</div><p id="project-count" role="status">7 projects</p></div>
<section class="project-gallery" aria-label="Project gallery">${projects.map((p,i)=>`<article class="project-card" data-category="${p.cat}" data-reveal><div class="project-art gallery-art art-${i%3}" aria-hidden="true"><span class="project-number">0${i+1}</span><span class="project-glyph">${p.symbol}</span><span class="art-label">${p.tags[0]}</span></div><div class="project-body"><p class="project-type">${p.type}</p><h2>${p.name}</h2><p>${p.text}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><div class="project-actions">${p.details?'<a class="text-link" href="project-dms.html">Project story ↗</a>':''}<a class="text-link" href="https://github.com/maysasfour/${p.repo}" target="_blank" rel="noopener noreferrer">View code ↗</a></div></div></article>`).join('')}</section>${cta}`);
page('project-dms','Disaster Management project','A closer look at Mays Suhail’s Disaster Management graduation project: Flutter, React, and Spring Boot.',`
<section class="page-intro" data-reveal><a class="text-link" href="projects.html">← All projects</a><p class="eyebrow">Graduation project / Web + mobile</p><h1>Technology for<br><em>better coordination.</em></h1><p class="lead">Disaster Management System — a project connecting citizens, responders, and administrators through web and mobile experiences.</p><div class="actions"><a class="button button-light" href="https://github.com/maysasfour/DMS" target="_blank" rel="noopener noreferrer">Explore the repository ↗</a><a class="text-link" href="contact.html">Discuss a similar idea ↗</a></div></section>
<div class="project-overview" data-reveal><div><span>PROJECT TYPE</span><strong>Graduation project</strong></div><div><span>INTERFACES</span><strong>Flutter &amp; React</strong></div><div><span>BACKEND</span><strong>Spring Boot REST API</strong></div></div>
<section class="case-section" data-reveal><p class="eyebrow">The idea</p><div><h2>A shared picture when information matters.</h2><p>The project explores how incident reporting, emergency resources, and coordination can come together in one system. Different interfaces support citizens, responders, and administrators.</p><p>It is an academic project, with source code and setup instructions available on GitHub.</p></div></section>
<section class="services-section"><div class="section-heading"><div><p class="eyebrow">Inside the project</p><h2>Connected features, clear roles.</h2></div></div><div class="principle-grid"><article data-reveal><span class="service-icon">◎</span><h3>Reporting &amp; awareness</h3><p>Incident reports, maps, emergency SOS, weather, news, and safety guidance.</p></article><article data-reveal><span class="service-icon">↔</span><h3>Coordination</h3><p>Shelter information, notifications, and resource and team management.</p></article><article data-reveal><span class="service-icon">◐</span><h3>Adaptable interfaces</h3><p>Multiple languages and light/dark themes across the application.</p></article></div></section>
<section class="case-section" data-reveal><p class="eyebrow">The technical side</p><div><h2>Web and mobile, connected by an API.</h2><p>The Flutter application uses Riverpod, GoRouter, Dio, and Hive. The repository also includes a React web frontend and the shared Spring Boot backend.</p><div class="architecture" aria-label="React web and Flutter mobile both connect to a Spring Boot API"><span>React web</span><span aria-hidden="true">↘</span><strong>Spring Boot API</strong><span aria-hidden="true">↗</span><span>Flutter mobile</span></div><a class="text-link" href="https://github.com/maysasfour/DMS#readme" target="_blank" rel="noopener noreferrer">Read the technical documentation ↗</a></div></section>${cta}`);

for(const name of ['index.html','services.html','contact.html','404.html']) {
 let html=read(name).replace(/<header[\s\S]*?<\/header>/,nav(name.split('.')[0]));
 if(name==='index.html') {
  html=html.replace('I’m a freelance web developer who builds clean websites, interactive experiences, and creative digital visuals with clear user-focused structure.','I’m a software engineer and freelance creative in Amman. I build websites, interactive experiences, and digital visuals that bring your ideas to life.');
  html=html.replace(/<section class="about-preview"[\s\S]*?<\/section>/,`<section class="about-preview" data-reveal><p class="eyebrow">03 / Beyond the interface</p><div><h2>One idea.<br><em>Many moving parts.</em></h2><p>My Disaster Management graduation project brings together a Flutter application, a React website, and a Spring Boot API.</p><div class="actions"><a class="button button-light" href="project-dms.html">Explore the project story ↗</a><a class="text-link" href="about.html">Meet the person behind it ↗</a></div></div><span class="large-spark" aria-hidden="true">✳</span></section>`);
 }
 if(name==='contact.html') {
  html=html.replace(/<section class="contact-banner"[\s\S]*?<\/section>/,`<section class="contact-banner" data-reveal><div><p class="eyebrow">Prefer a simple hello?</p><h2>My inbox is open.</h2><p>Email me directly or connect on LinkedIn.</p></div><a class="button button-light" href="mailto:mays.suhail@gmail.com">Email Mays ↗</a></section>`);
  html=html.replace('<form data-service-form novalidate>','<form data-service-form action="mailto:mays.suhail@gmail.com" method="get">');
  html=html.replace('id="fullName" name="fullName"','id="fullName" name="fullName" autocomplete="name" maxlength="100"');
  html=html.replace('id="email" name="email"','id="email" name="email" autocomplete="email" maxlength="200"');
  html=html.replace('id="message" name="message"','id="message" name="message" maxlength="2000"');
  html=html.replace('Simple, clear project contact.','Let’s find the right starting point.');
  html=html.replace('When you submit, your email app opens with a complete draft so contacting me is fast and organized.','The form opens a draft in your email app. Review it and press send there.');
  html=html.replace('</div>\n    </div>\n    <div class="inquiry-card"',`</div><button type="button" class="text-link copy-email">Copy email address ⧉</button><p id="copy-status" role="status"></p>\n    </div>\n    <div class="inquiry-card"`);
 }
 if(name==='services.html') {
  html=html.replace('Complete website pages built for performance, responsiveness, and clear storytelling.','A website shaped around your business, portfolio, or launch, with clear content and responsive layouts.');
  html=html.replace(/<section class="contact-banner"/,`<section class="faq-section"><div class="section-heading"><div><p class="eyebrow">Before we start</p><h2>A few useful answers.</h2></div></div><details><summary>How do we get started?</summary><p>Send your idea, any references, and your preferred timeline through the contact page. We’ll discuss scope and agree on the next steps.</p></details><details><summary>How much will my project cost?</summary><p>Pricing depends on the pages, features, and assets you need. Share your requirements and budget so we can discuss a suitable scope before work begins.</p></details><details><summary>Can you improve an existing website?</summary><p>Yes. Share the current site and the changes you have in mind, such as layout updates, mobile fixes, or new interactions.</p></details><details><summary>Do I need a domain first?</summary><p>You can start without one. We can discuss a suitable hosting address and connect a custom domain when you’re ready.</p></details></section><section class="contact-banner"`);
 }
 write(name,html);
}
// Make the public identity discoverable without inventing a production URL.
const identity={"@context":"https://schema.org","@type":"Person",name:"Mays Suhail",jobTitle:"Software Engineer & Freelance Developer",email:"mailto:mays.suhail@gmail.com",sameAs:["https://github.com/maysasfour","https://www.linkedin.com/in/mayssuhail/"],alumniOf:{"@type":"CollegeOrUniversity",name:"Middle East University"},homeLocation:{"@type":"Place",name:"Amman, Jordan"}};
write('index.html',read('index.html').replace('</head>',`<script type="application/ld+json">${JSON.stringify(identity)}</script>\n</head>`));
